export const LinkConfig = {
    siteUrl: 'https://frontend-content.ru/',
    chainOfResponsibility: '/patterns/behavioral/chainOfResponsibility/',
    command: "/patterns/behavioral/command/",
    interpreter: "/patterns/behavioral/interpreter/",
    iterator: "/patterns/behavioral/iterator/",
    mediator: "/patterns/behavioral/mediator/",
    memento: "/patterns/behavioral/memento/",
    observer: "/patterns/behavioral/observer/",
    state: "/patterns/behavioral/state/",
    strategy: "/patterns/behavioral/strategy/",
    templateMethod: "/patterns/behavioral/templateMethod/",
    visitor: "/patterns/behavioral/visitor/",
    abstractFactory: "/patterns/creational/abstractFactory/",
    builder: "/patterns/creational/builder/",
    factoryMethod: "/patterns/creational/factoryMethod/",
    prototype: "/patterns/creational/prototype/",
    singleton: "/patterns/creational/singleton/",
    adapter: "/patterns/structural/adapter/",
    bridge: "/patterns/structural/bridge/",
    composite: "/patterns/structural/composite/",
    decorator: "/patterns/structural/decorator/",
    facade: "/patterns/structural/facade/",
    flyweight: "/patterns/structural/flyweight/",
    proxy: "/patterns/structural/proxy/",
    index: "/",
};
