export const LinkConfig = {
    chainOfResponsibility: "/articles/chainOfResponsibility",
    command: "/articles/command",
    interpreter: "/articles/interpreter",
    iterator: "/articles/iterator",
    mediator: "/articles/mediator",
    memento: "/articles/memento",
    observer: "/articles/observer",
    state: "/articles/state",
    strategy: "/articles/strategy",
    templateMethod: "/articles/templateMethod",
    visitor: "/articles/visitor",
    abstractFactory: "/articles/abstractFactory",
    builder: "/articles/builder",
    factoryMethod: "/articles/factoryMethod",
    prototype: "/articles/prototype",
    singleton: "/articles/singleton",
    adapter: "/articles/adapter",
    bridge: "/articles/bridge",
    composite: "/articles/composite",
    decorator: "/articles/decorator",
    facade: "/articles/facade",
    flyweight: "/articles/flyweight",
    proxy: "/articles/proxy",
    main: "/",
};
