export default [
    {
        category: 'Порождающие',
        name: 'Порождающие',
        id: '1',
        patterns: [
            {category: 'abstractFactory', name: 'Абстрактная фабрика', id: '11'},
            {category: 'builder', name: 'Строитель', id: '12'},
            {category: 'factoryMethod', name: 'Фабричный метод', id: '13'},
            {category: 'prototype', name: 'Прототип', id: '14'},
            {category: 'singleton', name: 'Одиночка', id: '15'},
        ],
    },
    {
        category: 'Структурные',
        name: 'Структурные',
        id: '2',
        patterns: [
            {category: 'adapter', name: 'Адаптер', id: '21'},
            {category: 'bridge', name: 'Мост', id: '22'},
            {category: 'composite', name: 'Компоновщик', id: '23'},
            {category: 'decorator', name: 'Декоратор', id: '24'},
            {category: 'facade', name: 'Фасад', id: '25'},
            {category: 'flyweight', name: 'Приспособленец', id: '26'},
            {category: 'proxy', name: 'Заместитель', id: '27'},
        ],
    },
    {
        category: 'Поведенческие',
        name: 'Поведенческие',
        id: '3',
        patterns: [
            {category: 'chainOfResponsibility', name: 'Цепочка обязанностей', id: '31'},
            {category: 'command', name: 'Команда', id: '32'},
            {category: 'interpreter', name: 'Интерпретатор', id: '33'},
            {category: 'iterator', name: 'Итератор', id: '34'},
            {category: 'mediator', name: 'Посредник', id: '35'},
            {category: 'memento', name: 'Хранитель', id: '36'},
            {category: 'observer', name: 'Наблюдатель', id: '37'},
            {category: 'state', name: 'Состояние', id: '38'},
            {category: 'strategy', name: 'Стратегия', id: '39'},
            {category: 'templateMethod', name: 'Шаблонный метод', id: '40'},
            {category: 'visitor', name: 'Посетитель', id: '41'},
        ],
    },
];
